"""py-identity-model: OAuth2.0 and OpenID Connect Client Library

Provides both synchronous and asynchronous APIs for OpenID Connect operations.
"""

# Initialize SSL compatibility for backward compatibility with requests library
from . import ssl_config  # noqa: F401

# Backward compatible sync exports (default)
from .exceptions import (
    AuthorizeCallbackException,
    ConfigurationException,
    DiscoveryException,
    FailedResponseAccessError,
    InvalidAudienceException,
    InvalidIssuerException,
    JwksException,
    NetworkException,
    PyIdentityModelException,
    SignatureVerificationException,
    SuccessfulResponseAccessError,
    TokenExpiredException,
    TokenRequestException,
    TokenValidationException,
    UserInfoException,
    ValidationException,
)

# Identity models (shared)
from .identity import Claim, ClaimsIdentity, ClaimsPrincipal, to_principal
from .sync import (
    FAPI2_ALLOWED_AUTH_METHODS,
    FAPI2_ALLOWED_SIGNING_ALGORITHMS,
    FAPI2_REQUIRED_PKCE_METHOD,
    FAPI2_REQUIRED_RESPONSE_TYPE,
    AuthorizationCodeTokenRequest,
    AuthorizationCodeTokenResponse,
    AuthorizeCallbackResponse,
    AuthorizeCallbackValidationResult,
    BaseRequest,
    BaseResponse,
    ClientCredentialsTokenRequest,
    ClientCredentialsTokenResponse,
    DeviceAuthorizationRequest,
    DeviceAuthorizationResponse,
    DeviceTokenRequest,
    DeviceTokenResponse,
    DiscoveryDocumentRequest,
    DiscoveryDocumentResponse,
    DPoPKey,
    FAPIValidationResult,
    HTTPClient,
    JsonWebAlgorithmsKeyTypes,
    JsonWebKey,
    JsonWebKeyParameterNames,
    JwksRequest,
    JwksResponse,
    PushedAuthorizationRequest,
    PushedAuthorizationResponse,
    RefreshTokenRequest,
    RefreshTokenResponse,
    StateValidationResult,
    TokenExchangeRequest,
    TokenExchangeResponse,
    TokenIntrospectionRequest,
    TokenIntrospectionResponse,
    TokenRevocationRequest,
    TokenRevocationResponse,
    TokenValidationConfig,
    UserInfoRequest,
    UserInfoResponse,
    build_authorization_url,
    build_dpop_headers,
    build_jar_authorization_url,
    compute_ath,
    create_dpop_proof,
    create_request_object,
    exchange_token,
    generate_code_challenge,
    generate_code_verifier,
    generate_dpop_key,
    generate_pkce_pair,
    get_discovery_document,
    get_jwks,
    get_userinfo,
    introspect_token,
    jwks_from_dict,
    parse_authorize_callback_response,
    poll_device_token,
    push_authorization_request,
    refresh_token,
    request_authorization_code_token,
    request_client_credentials_token,
    request_device_authorization,
    revoke_token,
    validate_authorize_callback_state,
    validate_fapi_authorization_request,
    validate_fapi_client_config,
    validate_fapi_discovery,
    validate_token,
)


__all__ = [
    # FAPI 2.0
    "FAPI2_ALLOWED_AUTH_METHODS",
    "FAPI2_ALLOWED_SIGNING_ALGORITHMS",
    "FAPI2_REQUIRED_PKCE_METHOD",
    "FAPI2_REQUIRED_RESPONSE_TYPE",
    # Auth Code + PKCE
    "AuthorizationCodeTokenRequest",
    "AuthorizationCodeTokenResponse",
    # Authorize Callback
    "AuthorizeCallbackException",
    "AuthorizeCallbackResponse",
    "AuthorizeCallbackValidationResult",
    # Base Classes
    "BaseRequest",
    "BaseResponse",
    # Identity models
    "Claim",
    "ClaimsIdentity",
    "ClaimsPrincipal",
    "ClientCredentialsTokenRequest",
    "ClientCredentialsTokenResponse",
    "ConfigurationException",
    # DPoP
    "DPoPKey",
    # Device Authorization Grant
    "DeviceAuthorizationRequest",
    "DeviceAuthorizationResponse",
    "DeviceTokenRequest",
    "DeviceTokenResponse",
    # Request/Response models
    "DiscoveryDocumentRequest",
    "DiscoveryDocumentResponse",
    "DiscoveryException",
    "FAPIValidationResult",
    "FailedResponseAccessError",
    # HTTP Client
    "HTTPClient",
    "InvalidAudienceException",
    "InvalidIssuerException",
    "JsonWebAlgorithmsKeyTypes",
    "JsonWebKey",
    "JsonWebKeyParameterNames",
    "JwksException",
    "JwksRequest",
    "JwksResponse",
    "NetworkException",
    # PAR
    "PushedAuthorizationRequest",
    "PushedAuthorizationResponse",
    # Exceptions
    "PyIdentityModelException",
    # Refresh Token
    "RefreshTokenRequest",
    "RefreshTokenResponse",
    "SignatureVerificationException",
    "StateValidationResult",
    "SuccessfulResponseAccessError",
    # Token Exchange
    "TokenExchangeRequest",
    "TokenExchangeResponse",
    "TokenExpiredException",
    # Token Introspection
    "TokenIntrospectionRequest",
    "TokenIntrospectionResponse",
    "TokenRequestException",
    # Token Revocation
    "TokenRevocationRequest",
    "TokenRevocationResponse",
    "TokenValidationConfig",
    "TokenValidationException",
    "UserInfoException",
    "UserInfoRequest",
    "UserInfoResponse",
    "ValidationException",
    "build_authorization_url",
    "build_dpop_headers",
    "build_jar_authorization_url",
    "compute_ath",
    "create_dpop_proof",
    "create_request_object",
    "exchange_token",
    "generate_code_challenge",
    "generate_code_verifier",
    "generate_dpop_key",
    "generate_pkce_pair",
    # Sync API (default)
    "get_discovery_document",
    "get_jwks",
    "get_userinfo",
    "introspect_token",
    "jwks_from_dict",
    "parse_authorize_callback_response",
    "poll_device_token",
    "push_authorization_request",
    "refresh_token",
    "request_authorization_code_token",
    "request_client_credentials_token",
    "request_device_authorization",
    "revoke_token",
    "to_principal",
    "validate_authorize_callback_state",
    "validate_fapi_authorization_request",
    "validate_fapi_client_config",
    "validate_fapi_discovery",
    "validate_token",
]
