services:
  identityserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py-identity-model-identityserver
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./Config.cs:/app/Config.cs:ro
      - ./appsettings.json:/app/appsettings.json:ro
      - ./certs:/https:ro
    networks:
      - identity-network
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:443/.well-known/openid-configuration"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  identity-network:
    driver: bridge