name: Build

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      run-descope-integration: true
      run-example-tests: true
      run-build: true
    secrets: inherit
