name: Check PR

on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - uses: rayepps/require-semver-bump@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-regex-pattern: >
            VERSION = \\'(.+?)\\'
          version-file-path: 'setup.py'