name: Publish Distribution 📦

on:
  push:
    branches:
      - main
      - chore/move-to-uv

permissions:
  contents: read

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: make ci-setup
      - name: Build distribution 📦
        run: make build-dist
      - name: Publish distribution 📦 to PyPI
        env:
           UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: >
          make upload-dist