name: Publish Distribution 📦

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+rc[0-9]+"
      - "[0-9]+.[0-9]+[ab][0-9]+"
    branches:
      - feature/move-to-uv

permissions:
  contents: read

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.12
        uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install dependencies
        run: make ci-setup
      - name: Set tag version
        id: vars
        run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT
      - name: Build distribution 📦
        run: |
          echo ${{ steps.vars.outputs.tag }}
          sed -i -e "s/0.0.0/${{ steps.vars.outputs.tag }}/" pyproject.toml
          make build-dist
      - name: Publish distribution 📦 to PyPI
        env:
           UV_PUBLISH_TOKEN: ${{ secrets.pypi_token }}
        run: |
          make upload-dist